-- Settings
INSERT INTO `$prefix_settings` (`key` , `value`) VALUES ("version", "0");
INSERT INTO `$prefix_settings` (`key` , `value`) VALUES ("ping", "120");
INSERT INTO `$prefix_settings` (`key` , `value`) VALUES ("show_welcome_messages", "1");
INSERT INTO `$prefix_settings` (`key` , `value`) VALUES ("welcome_message", "Welcome, <PLAYER>!");
INSERT INTO `$prefix_settings` (`key` , `value`) VALUES ("show_first_join_message", "1");
INSERT INTO `$prefix_settings` (`key` , `value`) VALUES ("first_join_message", "Welcome, <PLAYER>! Your statistics on this server are now being tracked.");

-- Server Statistics
INSERT INTO `$prefix_server_statistics` (`key` , `value`) VALUES ("first_startup", "0");
INSERT INTO `$prefix_server_statistics` (`key` , `value`) VALUES ("last_startup", "0");
INSERT INTO `$prefix_server_statistics` (`key` , `value`) VALUES ("last_shutdown", "0");
INSERT INTO `$prefix_server_statistics` (`key` , `value`) VALUES ("current_uptime", "0");
INSERT INTO `$prefix_server_statistics` (`key` , `value`) VALUES ("total_uptime", "0");
INSERT INTO `$prefix_server_statistics` (`key` , `value`) VALUES ("max_players_online", "0");

-- Materials
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("1", "0", "stone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2", "0", "grass_side");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("3", "0", "dirt");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("4", "0", "stonebrick");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("5", "0", "wood");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("5", "1", "wood_spruce");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("5", "2", "wood_birch");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("5", "3", "wood_jungle");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("6", "0", "sapling");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("6", "1", "sapling_spruce");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("6", "2", "sapling_birch");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("6", "3", "sapling_jungle");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("7", "0", "bedrock");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("8", "0", "water");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("9", "0", "water_flow");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("10", "0", "lava");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("11", "0", "lava_flow");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("12", "0", "sand");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("13", "0", "gravel");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("14", "0", "oreGold");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("15", "0", "oreIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("16", "0", "oreCoal");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("17", "0", "tree_side");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("17", "1", "tree_spruce");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("17", "2", "tree_birch");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("17", "3", "tree_jungle");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("18", "0", "leaves");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("18", "1", "leaves_spruce");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("18", "2", "leaves_birch");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("18", "3", "leaves_jungle");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("19", "0", "sponge");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("20", "0", "glass");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("21", "0", "oreLapis");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("22", "0", "blockLapis");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("23", "0", "dispenser_front");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("24", "0", "sandstone_side");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("24", "1", "sandstone_carved");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("24", "2", "sandstone_smooth");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("25", "0", "musicBlock");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("26", "0", "bed");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("27", "0", "goldenRail");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("28", "0", "detectorRail");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("29", "0", "piston_top_sticky");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("30", "0", "web");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("31", "0", "thingrass_top");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("31", "1", "tall_grass");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("31", "2", "fern");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("32", "0", "deadbush");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("33", "0", "piston_top");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("34", "0", "piston_top");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "0", "cloth_0");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "1", "cloth_1");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "2", "cloth_2");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "3", "cloth_3");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "4", "cloth_4");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "5", "cloth_5");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "6", "cloth_6");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "7", "cloth_7");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "8", "cloth_8");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "9", "cloth_9");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "10", "cloth_10");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "11", "cloth_11");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "12", "cloth_12");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "13", "cloth_13");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "14", "cloth_14");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("35", "15", "cloth_15");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("36", "0", "");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("37", "0", "flower");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("38", "0", "rose");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("39", "0", "mushroom_brown");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("40", "0", "mushroom_red");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("41", "0", "blockGold");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("42", "0", "blockIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("43", "0", "stoneslab_side");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("44", "0", "stoneslab_top");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("44", "1", "sandstone_bottom");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("44", "2", "stonebrick");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("44", "3", "stonebricksmooth");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("44", "4", "brick");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("44", "5", "stonebrick");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("44", "6", "wood");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("45", "0", "brick");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("46", "0", "tnt_side");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("47", "0", "bookshelf");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("48", "0", "stoneMoss");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("49", "0", "obsidian");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("50", "0", "torch");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("51", "0", "fire_0");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("52", "0", "mobSpawner");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("53", "0", "wooden_stairs");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("54", "0", "chest");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("55", "0", "redstone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("56", "0", "oreDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("57", "0", "blockDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("58", "0", "workbench_front");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("59", "0", "seeds");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("60", "0", "farmland_dry");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("61", "0", "furnace_front");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("62", "0", "furnace_front_lit");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("63", "0", "signpost");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("64", "0", "doorWood_upper");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("65", "0", "ladder");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("66", "0", "rail");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("67", "0", "cobblestone_stairs");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("68", "0", "wall_sign");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("69", "0", "lever");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("70", "0", "stone_pressure_plate");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("71", "0", "doorIron_upper");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("72", "0", "wooden_pressure_plate");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("73", "0", "oreRedstone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("74", "0", "oreRedstone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("75", "0", "redtorch");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("76", "0", "redtorch_lit");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("77", "0", "stone_button");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("78", "0", "snow_side");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("79", "0", "ice");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("80", "0", "snow");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("81", "0", "cactus_side");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("82", "0", "clay");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("83", "0", "reeds");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("84", "0", "jukebox_top");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("85", "0", "fence");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("86", "0", "pumpkin_face");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("87", "0", "hellrock");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("88", "0", "hellsand");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("89", "0", "lightgen");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("90", "0", "portal");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("91", "0", "pumpkin_jack");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("92", "0", "cake");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("95", "0", "locked_chest");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("96", "0", "trapdoor");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("97", "0", "monster_egg");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("98", "0", "stonebricksmooth");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("98", "1", "stonebricksmooth_cracked");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("98", "2", "stonebricksmooth_mossy");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("98", "3", "stonebricksmooth_carved");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("99", "0", "mushroom_skin_brown");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("100", "0", "mushroom_skin_red");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("101", "0", "fenceIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("102", "0", "glass_pane");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("103", "0", "melon_side");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("106", "0", "vine");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("107", "0", "fence_gate");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("108", "0", "brick_stairs");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("109", "0", "stone_brick_stairs");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("110", "0", "mycel_side");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("111", "0", "waterlily");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("112", "0", "netherbrick");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("113", "0", "nether_brick_fence");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("114", "0", "nether_brick_stairs");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("116", "0", "enchantment_top");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("121", "0", "whiteStone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("122", "0", "dragonEgg");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("123", "0", "redstoneLight_lit");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("126", "0", "oak-wood_slab");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("126", "1", "spruce-wood_slab");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("126", "2", "birch-wood_slab");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("126", "3", "jungle-wood_slab");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("127", "0", "cocoa_2");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("128", "0", "sandstone_stairs");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("129", "0", "oreEmerald");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("130", "0", "ender_chest");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("133", "0", "blockEmerald");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("134", "0", "spruce_wood_stairs");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("135", "0", "birch_wood_stairs");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("136", "0", "jungle_wood_stairs");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("137", "0", "commandBlock");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("138", "0", "beacon");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("139", "0", "cobblestone_wall");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("139", "1", "mossy_cobblestone_wall");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("143", "0", "wooden_button");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("145", "0", "anvil_top");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("256", "0", "shovelIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("257", "0", "pickaxeIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("258", "0", "hatchetIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("259", "0", "flintAndSteel");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("260", "0", "apple");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("261", "0", "bow");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("262", "0", "arrow");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("263", "0", "coal");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("264", "0", "diamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("265", "0", "ingotIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("266", "0", "ingotGold");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("267", "0", "swordIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("268", "0", "swordWood");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("269", "0", "shovelWood");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("270", "0", "pickaxeWood");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("271", "0", "hatchetWood");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("272", "0", "swordStone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("273", "0", "shovelStone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("274", "0", "pickaxeStone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("275", "0", "hatchetStone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("276", "0", "swordDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("277", "0", "shovelDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("278", "0", "pickaxeDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("279", "0", "hatchetDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("280", "0", "stick");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("281", "0", "bowl");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("282", "0", "mushroomStew");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("283", "0", "swordGold");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("284", "0", "shovelGold");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("285", "0", "pickaxeGold");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("286", "0", "hatchetGold");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("287", "0", "string");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("288", "0", "feather");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("289", "0", "sulphur");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("290", "0", "hoeWood");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("291", "0", "hoeStone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("292", "0", "hoeIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("293", "0", "hoeDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("294", "0", "hoeGold");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("295", "0", "seeds");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("296", "0", "wheat");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("297", "0", "bread");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("298", "0", "helmetCloth");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("299", "0", "chestplateCloth");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("300", "0", "leggingsCloth");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("301", "0", "bootsCloth");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("302", "0", "helmetChain");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("303", "0", "chestplateChain");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("304", "0", "legginsChain");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("305", "0", "bootsChain");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("306", "0", "helmetIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("307", "0", "chestplateIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("308", "0", "leggingsIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("309", "0", "bootsIron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("310", "0", "helmetDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("311", "0", "chestplateDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("312", "0", "leggingsDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("313", "0", "bootsDiamond");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("314", "0", "gold_helmet");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("315", "0", "gold_chestplate");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("316", "0", "gold_leggings");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("317", "0", "gold_boots");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("318", "0", "flint");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("319", "0", "porkchopRaw");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("320", "0", "porkchopCooked");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("321", "0", "painting");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("322", "0", "appleGold");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("323", "0", "sign");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("324", "0", "doorWood_upper");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("325", "0", "bucket");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("326", "0", "bucketWater");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("327", "0", "bucketLava");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("328", "0", "minecart");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("329", "0", "saddle");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("330", "0", "iron_door");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("331", "0", "redstone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("332", "0", "snowball");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("333", "0", "boat");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("334", "0", "leather");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("335", "0", "milk");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("336", "0", "brick");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("337", "0", "balls");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("338", "0", "reeds");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("339", "0", "paper");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("340", "0", "book");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("341", "0", "slimeball");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("342", "0", "minecartChest");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("343", "0", "minecartFurnace");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("344", "0", "egg");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("345", "0", "compass");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("346", "0", "fishingRod");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("347", "0", "clock");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("348", "0", "yellowDust");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("349", "0", "fishRaw");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("350", "0", "fishCooked");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "0", "dyePoweder_black");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "1", "dyePoweder_red");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "2", "dyePoweder_green");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "3", "dyePoweder_brown");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "4", "dyePoweder_blue");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "5", "dyePoweder_purple");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "6", "dyePoweder_cyan");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "7", "dyePoweder_silver");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "8", "dyePoweder_gray");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "9", "dyePoweder_pink");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "10", "dyePoweder_lime");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "11", "dyePoweder_yellow");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "12", "dyePoweder_lightBlue");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "13", "dyePoweder_magenta");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "14", "dyePoweder_orange");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("351", "15", "dyePoweder_white");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("352", "0", "bone");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("353", "0", "sugar");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("354", "0", "cake");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("355", "0", "bed");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("356", "0", "diode");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("357", "0", "cookie");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("358", "0", "emptyMap");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("359", "0", "shears");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("360", "0", "melon");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("361", "0", "seeds_pumpkin");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("362", "0", "seeds_melon");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("363", "0", "beefRaw");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("364", "0", "beefCooked");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("365", "0", "chickenRaw");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("366", "0", "chickenCooked");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("367", "0", "rottenFlesh");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("368", "0", "enderPearl");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("369", "0", "blazeRod");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("370", "0", "ghastTear");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("373", "0", "potion");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("374", "0", "glassBottle");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("375", "0", "spiderEye");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("376", "0", "fermentedSpiderEye");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("377", "0", "blazePowder");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("378", "0", "magmaCream");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("379", "0", "brewingStand");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("380", "0", "cauldron");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("381", "0", "eyeOfEnder");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("382", "0", "speckledMelon");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "0", "spawn_creeper");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "1", "spawn_skeleton");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "2", "spawn_spider");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "3", "spawn_zombie");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "4", "spawn_slime");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "5", "spawn_ghast");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "6", "spawn_zombie_pigman");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "7", "spawn_enderman");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "8", "spawn_cave_spider");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "9", "spawn_silverfish");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "10", "spawn_blaze");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "11", "spawn_magma_cube");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "12", "spawn_pig");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "13", "spawn_sheep");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "14", "spawn_cow");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "15", "spawn_chicken");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "16", "spawn_squid");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "17", "spawn_wolf");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "18", "spawn_mooshroom");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "19", "spawn_ocelot");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("383", "20", "spawn_villager");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("384", "0", "expBottle");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("385", "0", "fireball");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("386", "0", "writingBook");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("387", "0", "writtenBook");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("388", "0", "emerald");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("390", "0", "flowerPot");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("391", "0", "carrots");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("392", "0", "potato");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("393", "0", "potatoBaked");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("394", "0", "potatoPoisonous");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("395", "0", "emptyMap");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("396", "0", "carrotGolden");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("397", "0", "skull_skeleton");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("397", "1", "skull_wither");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("397", "2", "skull_zombie");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("397", "3", "skull_char");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("397", "4", "skull_creeper");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("398", "0", "carrotOnAStick");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("399", "0", "netherStar");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("400", "0", "pumkpinPie");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("401", "0", "fireworks");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("402", "0", "fireworkCharge");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2256", "0", "record_13");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2257", "0", "record_cat");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2258", "0", "record_blocks");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2259", "0", "record_chirp");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2260", "0", "record_far");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2261", "0", "record_mall");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2262", "0", "record_mellohi");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2263", "0", "record_stal");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2264", "0", "record_strad");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2265", "0", "record_ward");
INSERT INTO `$prefix_materials` (`material_id` , `data` , `tp_name`) VALUES ("2266", "0", "record_11");

-- Entities
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("1", "item");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("2", "xporb");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("9", "painting");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("10", "arrow");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("11", "snowball");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("12", "fireball");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("13", "smallfireball");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("14", "thrownenderpearl");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("15", "eyeofendersignal");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("16", "thrownpotion");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("17", "thrownexpbottle");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("18", "itemframe");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("19", "witherskull");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("20", "primedtnt");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("21", "fallingsand");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("22", "fireworksrocketentity");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("41", "boat");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("42", "minecartrideable");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("43", "minecartchest");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("44", "minecartfurnace");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("45", "minecarthopper");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("46", "minecarthopper");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("47", "minecartspawner");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("48", "mob");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("49", "monster");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("50", "creeper");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("51", "skeleton");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("52", "skeleton_wither");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("53", "giant");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("54", "zombie");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("55", "slime");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("56", "ghast");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("57", "pigzombie");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("58", "enderman");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("59", "cavespider");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("60", "silverfish");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("61", "fire");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("62", "lava");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("63", "enderdragon-ender");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("64", "wither");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("66", "villager-witch");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("65", "bat");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("90", "pig");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("91", "sheep");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("92", "cow");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("93", "chicken");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("94", "squid");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("95", "wolf");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("96", "redcow");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("97", "snowman");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("98", "ozelot");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("99", "villager_golem");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("120", "villager-villager");
INSERT INTO `$prefix_entities` (`entity_id` , `tp_name`) VALUES ("200", "endercystal");