name: Statistics
main: com.wolvencraft.yasp.Statistics
version: 1.3.0
description: Extremely detailed player/server statistic tracking with web portal
website: http://dev.bukkit.org/bukkit-mods/Statistics/
authors: [pavog, bitWolfy, Dazzel_, MarioG1]
softdepend: [AdminCmd, BanHammer, Citizens, CommandBook, Factions, Jail, mcMMO, MobArena, PVPArena, Towny, VanishNoPacket, Vault, Vorifier, WorldEdit, WorldGuard]
load: POSTWORLD
commands:
  stats:
    description: Statistics commands
permissions:
  stats.track:
    description: Track the player statistics
    default: true
    children:
      stats.track.block: true
      stats.track.item: true
      stats.track.player: true
      stats.track.death: true
      stats.track.hook: true
  stats.track.block:
    description: Track player's block statistics
    children:
      stats.track.block.break: true
      stats.track.block.place: true
  stats.track.item:
    description: Track player's item statistics
    children:
      stats.track.item.drop: true
      stats.track.item.pickup: true
      stats.track.item.use: true
      stats.track.item.break: true
      stats.track.item.craft: true
      stats.track.item.anvil: true
      stats.track.item.misc: true
  stats.track.player:
    description: Track some basic player statistics
    children:
      stats.track.player.distances: true
      stats.track.player.inventory: true
      stats.track.player.misc: true
  stats.track.death:
    description: Track death and kill statistics
    children:
      stats.track.death.pvp: true
      stats.track.death.pve: true
      stats.track.death.other: true
  stats.track.hook:
    description: Track data from plugin hooks
    children:
      stats.track.hook.vault: true
  stats.cmd:
    description: Access to all statistics commands
    default: op
    children:
      stats.cmd.book: true
      stats.cmd.scoreboard: true
      stats.cmd.debug: true
      stats.cmd.remove: true